from __future__ import annotations

from tools.browser import (
    BROWSER_CLICK_TOOL,
    BROWSER_EXTRACT_TEXT_TOOL,
    BROWSER_FOLLOW_LINK_TOOL,
    BROWSER_INSPECT_PAGE_TOOL,
    BROWSER_OPEN_PAGE_TOOL,
    BROWSER_TYPE_TOOL,
)
from tools.desktop import (
    DESKTOP_CAPTURE_SCREENSHOT_TOOL,
    DESKTOP_CLICK_MOUSE_TOOL,
    DESKTOP_CLICK_POINT_TOOL,
    DESKTOP_FOCUS_WINDOW_TOOL,
    DESKTOP_GET_ACTIVE_WINDOW_TOOL,
    DESKTOP_HOVER_POINT_TOOL,
    DESKTOP_INSPECT_WINDOW_STATE_TOOL,
    DESKTOP_INSPECT_PROCESS_TOOL,
    DESKTOP_LIST_WINDOWS_TOOL,
    DESKTOP_LIST_PROCESSES_TOOL,
    DESKTOP_MOVE_MOUSE_TOOL,
    DESKTOP_OPEN_TARGET_TOOL,
    DESKTOP_PRESS_KEY_TOOL,
    DESKTOP_PRESS_KEY_SEQUENCE_TOOL,
    DESKTOP_RECOVER_WINDOW_TOOL,
    DESKTOP_RUN_COMMAND_TOOL,
    DESKTOP_SCROLL_TOOL,
    DESKTOP_START_PROCESS_TOOL,
    DESKTOP_STOP_PROCESS_TOOL,
    DESKTOP_TYPE_TEXT_TOOL,
    DESKTOP_WAIT_FOR_WINDOW_READY_TOOL,
)
from tools.email import (
    EMAIL_CONNECT_GMAIL_TOOL,
    EMAIL_LIST_THREADS_TOOL,
    EMAIL_PREPARE_FORWARD_DRAFT_TOOL,
    EMAIL_PREPARE_REPLY_DRAFT_TOOL,
    EMAIL_READ_THREAD_TOOL,
    EMAIL_SEND_DRAFT_TOOL,
)
from tools.files import APPLY_APPROVED_EDITS_TOOL, COMPARE_FILES_TOOL, INSPECT_PROJECT_TOOL, LIST_FILES_TOOL, READ_FILE_TOOL, SEARCH_FILES_TOOL
from tools.shell import DRAFT_PROPOSED_EDITS_TOOL, PLAN_PATCH_TOOL, REVIEW_BUNDLE_TOOL, RUN_SHELL_TOOL, SUGGEST_COMMANDS_TOOL


def get_browser_tools():
    return [
        BROWSER_OPEN_PAGE_TOOL,
        BROWSER_INSPECT_PAGE_TOOL,
        BROWSER_CLICK_TOOL,
        BROWSER_TYPE_TOOL,
        BROWSER_EXTRACT_TEXT_TOOL,
        BROWSER_FOLLOW_LINK_TOOL,
    ]


def get_desktop_tools():
    return [
        DESKTOP_LIST_WINDOWS_TOOL,
        DESKTOP_GET_ACTIVE_WINDOW_TOOL,
        DESKTOP_FOCUS_WINDOW_TOOL,
        DESKTOP_INSPECT_WINDOW_STATE_TOOL,
        DESKTOP_RECOVER_WINDOW_TOOL,
        DESKTOP_WAIT_FOR_WINDOW_READY_TOOL,
        DESKTOP_CAPTURE_SCREENSHOT_TOOL,
        DESKTOP_MOVE_MOUSE_TOOL,
        DESKTOP_HOVER_POINT_TOOL,
        DESKTOP_CLICK_MOUSE_TOOL,
        DESKTOP_CLICK_POINT_TOOL,
        DESKTOP_SCROLL_TOOL,
        DESKTOP_PRESS_KEY_TOOL,
        DESKTOP_PRESS_KEY_SEQUENCE_TOOL,
        DESKTOP_TYPE_TEXT_TOOL,
        DESKTOP_LIST_PROCESSES_TOOL,
        DESKTOP_INSPECT_PROCESS_TOOL,
        DESKTOP_START_PROCESS_TOOL,
        DESKTOP_STOP_PROCESS_TOOL,
        DESKTOP_RUN_COMMAND_TOOL,
        DESKTOP_OPEN_TARGET_TOOL,
    ]


def get_project_inspection_tools():
    return [
        INSPECT_PROJECT_TOOL,
        COMPARE_FILES_TOOL,
        READ_FILE_TOOL,
        LIST_FILES_TOOL,
        SEARCH_FILES_TOOL,
    ]


def get_email_tools():
    return [
        EMAIL_CONNECT_GMAIL_TOOL,
        EMAIL_LIST_THREADS_TOOL,
        EMAIL_READ_THREAD_TOOL,
        EMAIL_PREPARE_REPLY_DRAFT_TOOL,
        EMAIL_PREPARE_FORWARD_DRAFT_TOOL,
        EMAIL_SEND_DRAFT_TOOL,
    ]


def get_planning_tools():
    return [
        APPLY_APPROVED_EDITS_TOOL,
        SUGGEST_COMMANDS_TOOL,
        PLAN_PATCH_TOOL,
        DRAFT_PROPOSED_EDITS_TOOL,
        REVIEW_BUNDLE_TOOL,
        RUN_SHELL_TOOL,
    ]


def get_tools():
    inspection_tools = get_project_inspection_tools()
    return [
        inspection_tools[0],
        *get_email_tools(),
        *get_browser_tools(),
        *get_desktop_tools(),
        *inspection_tools[1:],
        *get_planning_tools(),
    ]
